import Foundation

public struct ChromeAdapter {
    public let paths: MacwalPaths
    public let fileSystem: FileSystem
    public let backupManager: BackupManager

    private var outputDirectory: URL {
        paths.generated.appendingPathComponent("chrome/macwal-theme", isDirectory: true)
    }

    public init(paths: MacwalPaths, fileSystem: FileSystem = FileSystem(), backupManager: BackupManager? = nil) {
        self.paths = paths
        self.fileSystem = fileSystem
        self.backupManager = backupManager ?? BackupManager(paths: paths, fileSystem: fileSystem)
    }

    public func preview() -> AdapterPlan {
        AdapterPlan(
            target: .chrome,
            status: "ready",
            plannedWrites: [
                outputDirectory.appendingPathComponent("manifest.json").path,
                outputDirectory.appendingPathComponent("README.md").path
            ],
            messages: ["Generates a Chrome Manifest V3 theme folder. Loading remains manual."]
        )
    }

    public func apply(palette: PaletteDocument, dryRun: Bool) throws -> AdapterApplySummary {
        let manifestURL = outputDirectory.appendingPathComponent("manifest.json")
        let readmeURL = outputDirectory.appendingPathComponent("README.md")
        let imageDirectory = outputDirectory.appendingPathComponent("images", isDirectory: true)
        let changedPaths = [manifestURL.path, readmeURL.path, imageDirectory.path]

        if dryRun {
            return AdapterApplySummary(
                target: .chrome,
                changedPaths: changedPaths,
                messages: ["Dry run: no Chrome theme files were written."]
            )
        }

        try backupManager.backupFileBeforeWrite(outputDirectory, adapter: .chrome, dryRun: false)
        try backupManager.backupFileBeforeWrite(imageDirectory, adapter: .chrome, dryRun: false)
        try fileSystem.ensureDirectory(imageDirectory)
        try backupManager.backupFileBeforeWrite(manifestURL, adapter: .chrome, dryRun: false)
        try backupManager.backupFileBeforeWrite(readmeURL, adapter: .chrome, dryRun: false)
        try fileSystem.atomicWriteString(try renderManifest(palette), to: manifestURL)
        try fileSystem.atomicWriteString(renderReadme(), to: readmeURL)

        return AdapterApplySummary(
            target: .chrome,
            changedPaths: changedPaths,
            messages: ["Chrome theme folder generated. Load it manually from chrome://extensions."]
        )
    }

    private func renderManifest(_ palette: PaletteDocument) throws -> String {
        let colors: [String: Any] = [
            "frame": try rgbArray(palette, "background"),
            "toolbar": try rgbArray(palette, "background"),
            "tab_text": try rgbArray(palette, "foreground"),
            "bookmark_text": try rgbArray(palette, "foreground"),
            "ntp_background": try rgbArray(palette, "background"),
            "ntp_text": try rgbArray(palette, "foreground"),
            "button_background": try rgbArray(palette, "accent")
        ]

        let manifest: [String: Any] = [
            "manifest_version": 3,
            "name": "macwal",
            "version": "0.1.0",
            "theme": [
                "colors": colors
            ]
        ]

        let data = try JSONSerialization.data(withJSONObject: manifest, options: [.prettyPrinted, .sortedKeys])
        return String(decoding: data, as: UTF8.self) + "\n"
    }

    private func renderReadme() -> String {
        """
        # macwal Chrome Theme

        Generated by macwal.

        To load:

        1. Open chrome://extensions.
        2. Enable Developer mode.
        3. Choose "Load unpacked".
        4. Select this `macwal-theme` directory.

        """
    }

    private func rgbArray(_ palette: PaletteDocument, _ key: String) throws -> [Int] {
        guard let hex = palette.colors[key] else {
            throw MacwalError.adapterFailed("Palette is missing required color '\(key)'.")
        }
        let rgb = try RGBColor(hex: hex)
        return [Int(rgb.red), Int(rgb.green), Int(rgb.blue)]
    }
}
