import Foundation

public struct ObsidianAdapter {
    public let paths: MacwalPaths
    public let config: MacwalConfig.ObsidianConfig
    public let fileSystem: FileSystem
    public let backupManager: BackupManager

    public init(
        paths: MacwalPaths,
        config: MacwalConfig.ObsidianConfig,
        fileSystem: FileSystem = FileSystem(),
        backupManager: BackupManager? = nil
    ) {
        self.paths = paths
        self.config = config
        self.fileSystem = fileSystem
        self.backupManager = backupManager ?? BackupManager(paths: paths, fileSystem: fileSystem)
    }

    public func preview() -> AdapterPlan {
        guard !config.vaults.isEmpty else {
            return AdapterPlan(
                target: .obsidian,
                status: "blocked",
                messages: ["No Obsidian vaults are configured in config.json."]
            )
        }

        return AdapterPlan(
            target: .obsidian,
            status: "ready",
            plannedWrites: plannedWrites(),
            messages: ["Writes and enables the macwal CSS snippet in configured Obsidian vaults."]
        )
    }

    public func apply(palette: PaletteDocument, dryRun: Bool) throws -> AdapterApplySummary {
        guard !config.vaults.isEmpty else {
            throw MacwalError.missingPrerequisite("No Obsidian vaults are configured. Add vault paths to config.json before applying target 'obsidian'.")
        }

        let snippets = snippetURLs()
        let changedPaths = plannedWrites()
        if dryRun {
            return AdapterApplySummary(
                target: .obsidian,
                changedPaths: changedPaths,
                messages: ["Dry run: no Obsidian files were written."]
            )
        }

        let css = try renderCSS(palette)
        for url in snippets {
            let appearanceURL = appearanceURL(forSnippetURL: url)
            try backupManager.backupFileBeforeWrite(url.deletingLastPathComponent(), adapter: .obsidian, dryRun: false)
            try backupManager.backupFileBeforeWrite(url, adapter: .obsidian, dryRun: false)
            try backupManager.backupFileBeforeWrite(appearanceURL, adapter: .obsidian, dryRun: false)
            try fileSystem.atomicWriteString(css, to: url)
            try enableSnippet(in: appearanceURL)
        }

        return AdapterApplySummary(
            target: .obsidian,
            changedPaths: changedPaths,
            messages: ["Obsidian snippet written and enabled in appearance.json."]
        )
    }

    private func snippetURLs() -> [URL] {
        config.vaults.map { vaultPath in
            URL(fileURLWithPath: vaultPath)
                .appendingPathComponent(".obsidian/snippets/macwal.css")
        }
    }

    private func appearanceURL(forSnippetURL snippetURL: URL) -> URL {
        snippetURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("appearance.json")
    }

    private func plannedWrites() -> [String] {
        snippetURLs().flatMap { snippetURL in
            [
                snippetURL.path,
                appearanceURL(forSnippetURL: snippetURL).path
            ]
        }
    }

    private func enableSnippet(in appearanceURL: URL) throws {
        var appearance: [String: Any] = [:]
        if fileSystem.fileExists(appearanceURL) {
            let data = try Data(contentsOf: appearanceURL)
            if !data.isEmpty {
                guard let existing = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    throw MacwalError.adapterFailed("Obsidian appearance.json must contain a JSON object: \(appearanceURL.path)")
                }
                appearance = existing
            }
        }

        let existingSnippets = appearance["enabledCssSnippets"]
        var snippets: [String]
        if let values = existingSnippets as? [String] {
            snippets = values
        } else if existingSnippets == nil {
            snippets = []
        } else {
            throw MacwalError.adapterFailed("Obsidian enabledCssSnippets must be a string array: \(appearanceURL.path)")
        }

        if !snippets.contains("macwal") {
            snippets.append("macwal")
        }
        appearance["enabledCssSnippets"] = snippets

        let data = try JSONSerialization.data(withJSONObject: appearance, options: [.prettyPrinted, .sortedKeys])
        try fileSystem.atomicWrite(data + Data([0x0A]), to: appearanceURL)
    }

    private func renderCSS(_ palette: PaletteDocument) throws -> String {
        func color(_ key: String) throws -> String {
            guard let value = palette.colors[key] else {
                throw MacwalError.adapterFailed("Palette is missing required color '\(key)'.")
            }
            return value
        }

        let accent = try color("accent")
        return """
        /* Generated by macwal. Do not edit by hand. */

        body {
          --background-primary: \(try color("background"));
          --background-secondary: \(try color("brightBlack"));
          --text-normal: \(try color("foreground"));
          --text-muted: \(try color("white"));
          --text-accent: \(accent);
          --interactive-accent: \(accent);
          --interactive-accent-hover: \(try color("brightCyan"));
          --h1-color: \(try color("brightRed"));
          --h2-color: \(try color("brightYellow"));
          --h3-color: \(try color("brightGreen"));
          --h4-color: \(try color("brightCyan"));
          --h5-color: \(try color("brightBlue"));
          --h6-color: \(try color("brightMagenta"));
        }

        """
    }
}
