import Foundation

public struct ObsidianAdapter {
    public let paths: MacwalPaths
    public let config: MacwalConfig.ObsidianConfig
    public let fileSystem: FileSystem
    public let backupManager: BackupManager

    public init(
        paths: MacwalPaths,
        config: MacwalConfig.ObsidianConfig,
        fileSystem: FileSystem = FileSystem(),
        backupManager: BackupManager? = nil
    ) {
        self.paths = paths
        self.config = config
        self.fileSystem = fileSystem
        self.backupManager = backupManager ?? BackupManager(paths: paths, fileSystem: fileSystem)
    }

    public func preview() -> AdapterPlan {
        guard !config.vaults.isEmpty else {
            return AdapterPlan(
                target: .obsidian,
                status: "blocked",
                messages: ["No Obsidian vaults are configured in config.json."]
            )
        }

        return AdapterPlan(
            target: .obsidian,
            status: "ready",
            plannedWrites: snippetURLs().map(\.path),
            messages: ["Writes macwal.css to configured Obsidian vault snippets folders."]
        )
    }

    public func apply(palette: PaletteDocument, dryRun: Bool) throws -> AdapterApplySummary {
        guard !config.vaults.isEmpty else {
            throw MacwalError.missingPrerequisite("No Obsidian vaults are configured. Add vault paths to config.json before applying target 'obsidian'.")
        }

        let snippets = snippetURLs()
        if dryRun {
            return AdapterApplySummary(
                target: .obsidian,
                changedPaths: snippets.map(\.path),
                messages: ["Dry run: no Obsidian snippets were written."]
            )
        }

        let css = try renderCSS(palette)
        for url in snippets {
            try backupManager.backupFileBeforeWrite(url.deletingLastPathComponent(), adapter: .obsidian, dryRun: false)
            try backupManager.backupFileBeforeWrite(url, adapter: .obsidian, dryRun: false)
            try fileSystem.atomicWriteString(css, to: url)
        }

        return AdapterApplySummary(
            target: .obsidian,
            changedPaths: snippets.map(\.path),
            messages: ["Obsidian snippet written. Enable the macwal snippet once in Obsidian Appearance settings."]
        )
    }

    private func snippetURLs() -> [URL] {
        config.vaults.map { vaultPath in
            URL(fileURLWithPath: vaultPath)
                .appendingPathComponent(".obsidian/snippets/macwal.css")
        }
    }

    private func renderCSS(_ palette: PaletteDocument) throws -> String {
        func color(_ key: String) throws -> String {
            guard let value = palette.colors[key] else {
                throw MacwalError.adapterFailed("Palette is missing required color '\(key)'.")
            }
            return value
        }

        let accent = try color("accent")
        return """
        /* Generated by macwal. Do not edit by hand.
           Enable this snippet once in Obsidian Settings > Appearance > CSS snippets. */

        body {
          --background-primary: \(try color("background"));
          --background-secondary: \(try color("brightBlack"));
          --text-normal: \(try color("foreground"));
          --text-muted: \(try color("white"));
          --text-accent: \(accent);
          --interactive-accent: \(accent);
          --interactive-accent-hover: \(try color("brightCyan"));
          --h1-color: \(try color("brightRed"));
          --h2-color: \(try color("brightYellow"));
          --h3-color: \(try color("brightGreen"));
          --h4-color: \(try color("brightCyan"));
          --h5-color: \(try color("brightBlue"));
          --h6-color: \(try color("brightMagenta"));
        }

        """
    }
}
