import Foundation

public struct ShellAdapter {
    public let paths: MacwalPaths
    public let fileSystem: FileSystem
    public let backupManager: BackupManager

    private var outputDirectory: URL {
        paths.generated.appendingPathComponent("shell", isDirectory: true)
    }

    public init(paths: MacwalPaths, fileSystem: FileSystem = FileSystem(), backupManager: BackupManager? = nil) {
        self.paths = paths
        self.fileSystem = fileSystem
        self.backupManager = backupManager ?? BackupManager(paths: paths, fileSystem: fileSystem)
    }

    public func preview() -> AdapterPlan {
        AdapterPlan(
            target: .shell,
            status: "ready",
            plannedWrites: outputFiles().map(\.path),
            messages: ["Writes generated theme files under Application Support."]
        )
    }

    public func apply(palette: PaletteDocument, dryRun: Bool) throws -> AdapterApplySummary {
        let files: [(URL, String)] = [
            (outputDirectory.appendingPathComponent("colors.sh"), renderShell(palette)),
            (outputDirectory.appendingPathComponent("colors.json"), renderColorsJSON(palette)),
            (outputDirectory.appendingPathComponent("colors.css"), renderCSS(palette)),
            (outputDirectory.appendingPathComponent("colors.Xresources"), renderXresources(palette))
        ]

        if dryRun {
            return AdapterApplySummary(
                target: .shell,
                changedPaths: files.map { $0.0.path },
                messages: ["Dry run: no shell files were written."]
            )
        }

        try backupManager.backupFileBeforeWrite(outputDirectory, adapter: .shell, dryRun: false)
        try fileSystem.ensureDirectory(outputDirectory)
        for (url, content) in files {
            try backupManager.backupFileBeforeWrite(url, adapter: .shell, dryRun: false)
            try fileSystem.atomicWriteString(content, to: url)
        }

        return AdapterApplySummary(
            target: .shell,
            changedPaths: files.map { $0.0.path },
            messages: ["Shell theme files written."]
        )
    }

    private func outputFiles() -> [URL] {
        [
            outputDirectory.appendingPathComponent("colors.sh"),
            outputDirectory.appendingPathComponent("colors.json"),
            outputDirectory.appendingPathComponent("colors.css"),
            outputDirectory.appendingPathComponent("colors.Xresources")
        ]
    }

    private func renderShell(_ palette: PaletteDocument) -> String {
        var lines = [
            "# Generated by macwal. Do not edit by hand.",
            "export MACWAL_PALETTE_SOURCE=\(shellQuote(palette.source.path))"
        ]
        for key in sortedColorKeys(palette) {
            lines.append("export MACWAL_COLOR_\(environmentName(key))=\(shellQuote(palette.colors[key] ?? ""))")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func renderColorsJSON(_ palette: PaletteDocument) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = (try? encoder.encode(palette.colors)) ?? Data("{}".utf8)
        return String(decoding: data, as: UTF8.self) + "\n"
    }

    private func renderCSS(_ palette: PaletteDocument) -> String {
        var lines = [
            "/* Generated by macwal. Do not edit by hand. */",
            ":root {"
        ]
        for key in sortedColorKeys(palette) {
            lines.append("  --macwal-color-\(cssName(key)): \(palette.colors[key] ?? "#000000");")
        }
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private func renderXresources(_ palette: PaletteDocument) -> String {
        var lines = ["! Generated by macwal. Do not edit by hand."]
        let mappings: [(String, String)] = [
            ("background", "*.background"),
            ("foreground", "*.foreground"),
            ("cursor", "*.cursorColor"),
            ("black", "*.color0"),
            ("red", "*.color1"),
            ("green", "*.color2"),
            ("yellow", "*.color3"),
            ("blue", "*.color4"),
            ("magenta", "*.color5"),
            ("cyan", "*.color6"),
            ("white", "*.color7"),
            ("brightBlack", "*.color8"),
            ("brightRed", "*.color9"),
            ("brightGreen", "*.color10"),
            ("brightYellow", "*.color11"),
            ("brightBlue", "*.color12"),
            ("brightMagenta", "*.color13"),
            ("brightCyan", "*.color14"),
            ("brightWhite", "*.color15")
        ]

        for (key, resource) in mappings {
            lines.append("\(resource): \(palette.colors[key] ?? "#000000")")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func sortedColorKeys(_ palette: PaletteDocument) -> [String] {
        palette.colors.keys.sorted()
    }

    private func cssName(_ name: String) -> String {
        var result = ""
        for scalar in name.unicodeScalars {
            if CharacterSet.uppercaseLetters.contains(scalar) {
                result.append("-")
                result.append(String(scalar).lowercased())
            } else {
                result.append(String(scalar))
            }
        }
        return result
    }

    private func environmentName(_ name: String) -> String {
        cssName(name).uppercased().replacingOccurrences(of: "-", with: "_")
    }

    private func shellQuote(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\\''"))'"
    }
}
